# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from risenlighten.lasvsim.process_task.api.cosim.v1 import simulation_pb2 as risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2


class CosimStub(object):
    """
    联合仿真服务
    以下是错误码定义:
    StartErrorCode    = -100
    TaskNotExistCode  = -200
    StopErrorCode     = -300
    MapErrorCode      = -400
    NextStepErrorCode = -500
    VehicleErrorCode  = -600
    ErrorCode         = -800

    仿真状态码:
    0    : 待开始
    1-99 : 运行中
    100  : 已完成
    -1   : 运行错误
    -100 : 任务非正常终止
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_unary(
                '/risenlighten.lasvsim.process_task.api.cosim.v1.Cosim/Start',
                request_serializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.StartSimulationReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.StartSimulationRes.FromString,
                )
        self.NextStep = channel.unary_unary(
                '/risenlighten.lasvsim.process_task.api.cosim.v1.Cosim/NextStep',
                request_serializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.NextStepReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.NextStepRes.FromString,
                )
        self.ResetSimulation = channel.unary_unary(
                '/risenlighten.lasvsim.process_task.api.cosim.v1.Cosim/ResetSimulation',
                request_serializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.ResetSimulationReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.ResetSimulationRes.FromString,
                )
        self.Stop = channel.unary_unary(
                '/risenlighten.lasvsim.process_task.api.cosim.v1.Cosim/Stop',
                request_serializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.StopSimulationReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.StopSimulationRes.FromString,
                )
        self.GetMap = channel.unary_unary(
                '/risenlighten.lasvsim.process_task.api.cosim.v1.Cosim/GetMap',
                request_serializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetMapReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetMapRes.FromString,
                )
        self.GetAllTrafficPart = channel.unary_unary(
                '/risenlighten.lasvsim.process_task.api.cosim.v1.Cosim/GetAllTrafficPart',
                request_serializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetAllTrafficPartReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetAllTrafficPartRes.FromString,
                )
        self.SetVehicleControl = channel.unary_unary(
                '/risenlighten.lasvsim.process_task.api.cosim.v1.Cosim/SetVehicleControl',
                request_serializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.SetVehicleControlReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.SetVehicleControlRes.FromString,
                )
        self.GetVehicle = channel.unary_unary(
                '/risenlighten.lasvsim.process_task.api.cosim.v1.Cosim/GetVehicle',
                request_serializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetVehicleReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetVehicleRes.FromString,
                )
        self.GetResults = channel.unary_unary(
                '/risenlighten.lasvsim.process_task.api.cosim.v1.Cosim/GetResults',
                request_serializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetResultsReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetResultsRes.FromString,
                )
        self.GetLink = channel.unary_unary(
                '/risenlighten.lasvsim.process_task.api.cosim.v1.Cosim/GetLink',
                request_serializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetLinkReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetLinkRes.FromString,
                )
        self.GetLane = channel.unary_unary(
                '/risenlighten.lasvsim.process_task.api.cosim.v1.Cosim/GetLane',
                request_serializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetLaneReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetLaneRes.FromString,
                )
        self.GetJunction = channel.unary_unary(
                '/risenlighten.lasvsim.process_task.api.cosim.v1.Cosim/GetJunction',
                request_serializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetJunctionReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetJunctionRes.FromString,
                )
        self.GetSegment = channel.unary_unary(
                '/risenlighten.lasvsim.process_task.api.cosim.v1.Cosim/GetSegment',
                request_serializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetSegmentReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetSegmentRes.FromString,
                )
        self.GetVehicleIdList = channel.unary_unary(
                '/risenlighten.lasvsim.process_task.api.cosim.v1.Cosim/GetVehicleIdList',
                request_serializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetVehicleIdListReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetVehicleIdListRes.FromString,
                )
        self.UpdateVehicleInfo = channel.unary_unary(
                '/risenlighten.lasvsim.process_task.api.cosim.v1.Cosim/UpdateVehicleInfo',
                request_serializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.UpdateVehicleInfoReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.UpdateVehicleInfoRes.FromString,
                )


class CosimServicer(object):
    """
    联合仿真服务
    以下是错误码定义:
    StartErrorCode    = -100
    TaskNotExistCode  = -200
    StopErrorCode     = -300
    MapErrorCode      = -400
    NextStepErrorCode = -500
    VehicleErrorCode  = -600
    ErrorCode         = -800

    仿真状态码:
    0    : 待开始
    1-99 : 运行中
    100  : 已完成
    -1   : 运行错误
    -100 : 任务非正常终止
    """

    def Start(self, request, context):
        """开始任务, 任务初始化
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NextStep(self, request, context):
        """执行仿真步骤
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetSimulation(self, request, context):
        """重置仿真
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """强制结束仿真
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMap(self, request, context):
        """获取全量地图
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllTrafficPart(self, request, context):
        """获取全量交通流信息(车辆)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVehicleControl(self, request, context):
        """修改车辆状态, lon_acc:纵向加速度, ste_wheel: 方向盘转速
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVehicle(self, request, context):
        """根据id获取自测车辆信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResults(self, request, context):
        """获取仿真结果数据 map<string, [][]float64> 多层嵌套结构
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLink(self, request, context):
        """根据LinkID获取link信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLane(self, request, context):
        """根据LaneID获取lane信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJunction(self, request, context):
        """根据junctionID获取junction信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSegment(self, request, context):
        """根据segmentID获取segment信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVehicleIdList(self, request, context):
        """获取车辆Id列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateVehicleInfo(self, request, context):
        """修改车辆信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CosimServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.StartSimulationReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.StartSimulationRes.SerializeToString,
            ),
            'NextStep': grpc.unary_unary_rpc_method_handler(
                    servicer.NextStep,
                    request_deserializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.NextStepReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.NextStepRes.SerializeToString,
            ),
            'ResetSimulation': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetSimulation,
                    request_deserializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.ResetSimulationReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.ResetSimulationRes.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.StopSimulationReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.StopSimulationRes.SerializeToString,
            ),
            'GetMap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMap,
                    request_deserializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetMapReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetMapRes.SerializeToString,
            ),
            'GetAllTrafficPart': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllTrafficPart,
                    request_deserializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetAllTrafficPartReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetAllTrafficPartRes.SerializeToString,
            ),
            'SetVehicleControl': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVehicleControl,
                    request_deserializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.SetVehicleControlReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.SetVehicleControlRes.SerializeToString,
            ),
            'GetVehicle': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVehicle,
                    request_deserializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetVehicleReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetVehicleRes.SerializeToString,
            ),
            'GetResults': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResults,
                    request_deserializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetResultsReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetResultsRes.SerializeToString,
            ),
            'GetLink': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLink,
                    request_deserializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetLinkReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetLinkRes.SerializeToString,
            ),
            'GetLane': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLane,
                    request_deserializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetLaneReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetLaneRes.SerializeToString,
            ),
            'GetJunction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJunction,
                    request_deserializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetJunctionReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetJunctionRes.SerializeToString,
            ),
            'GetSegment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSegment,
                    request_deserializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetSegmentReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetSegmentRes.SerializeToString,
            ),
            'GetVehicleIdList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVehicleIdList,
                    request_deserializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetVehicleIdListReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetVehicleIdListRes.SerializeToString,
            ),
            'UpdateVehicleInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateVehicleInfo,
                    request_deserializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.UpdateVehicleInfoReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.UpdateVehicleInfoRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'risenlighten.lasvsim.process_task.api.cosim.v1.Cosim', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Cosim(object):
    """
    联合仿真服务
    以下是错误码定义:
    StartErrorCode    = -100
    TaskNotExistCode  = -200
    StopErrorCode     = -300
    MapErrorCode      = -400
    NextStepErrorCode = -500
    VehicleErrorCode  = -600
    ErrorCode         = -800

    仿真状态码:
    0    : 待开始
    1-99 : 运行中
    100  : 已完成
    -1   : 运行错误
    -100 : 任务非正常终止
    """

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.process_task.api.cosim.v1.Cosim/Start',
            risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.StartSimulationReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.StartSimulationRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NextStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.process_task.api.cosim.v1.Cosim/NextStep',
            risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.NextStepReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.NextStepRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResetSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.process_task.api.cosim.v1.Cosim/ResetSimulation',
            risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.ResetSimulationReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.ResetSimulationRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.process_task.api.cosim.v1.Cosim/Stop',
            risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.StopSimulationReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.StopSimulationRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.process_task.api.cosim.v1.Cosim/GetMap',
            risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetMapReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetMapRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllTrafficPart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.process_task.api.cosim.v1.Cosim/GetAllTrafficPart',
            risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetAllTrafficPartReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetAllTrafficPartRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetVehicleControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.process_task.api.cosim.v1.Cosim/SetVehicleControl',
            risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.SetVehicleControlReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.SetVehicleControlRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVehicle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.process_task.api.cosim.v1.Cosim/GetVehicle',
            risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetVehicleReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetVehicleRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.process_task.api.cosim.v1.Cosim/GetResults',
            risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetResultsReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetResultsRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.process_task.api.cosim.v1.Cosim/GetLink',
            risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetLinkReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetLinkRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLane(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.process_task.api.cosim.v1.Cosim/GetLane',
            risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetLaneReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetLaneRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetJunction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.process_task.api.cosim.v1.Cosim/GetJunction',
            risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetJunctionReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetJunctionRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSegment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.process_task.api.cosim.v1.Cosim/GetSegment',
            risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetSegmentReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetSegmentRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVehicleIdList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.process_task.api.cosim.v1.Cosim/GetVehicleIdList',
            risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetVehicleIdListReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.GetVehicleIdListRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateVehicleInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.process_task.api.cosim.v1.Cosim/UpdateVehicleInfo',
            risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.UpdateVehicleInfoReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_process__task_dot_api_dot_cosim_dot_v1_dot_simulation__pb2.UpdateVehicleInfoRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
